### ISSUE TITLE
UI processing screen

### ISSUE THREAD

**Issue by jkatz35** [bglowniak/Air-Quality-Analysis#29]
Currently, UI calls back-end while on home screen, then goes to processing screen after back-end returns. This makes the application appear to malfunction or be buggy. To fix, make the UI switch to a processing screen before calling the back-end, so the UI displays that the application is working on the results.

**Comment by p13i** [comment]
Done in this commit: https://github.com/bglowniak/Air-Quality-Analysis/commit/eb847042d3cd0d308f431120dc5628460241e609

Will submit PR when Austin and I wrap up the PDF generation script.

**Comment by bglowniak** [comment]
Fixed in 9543110a58ce5c6edb30f1e3bfe8e03233ab6e86

The app now correctly switches to the progress screen and runs a loading icon while the app performs its functions by using a worker thread to run the data analysis process. This was significantly harder than I expected it to be. After a lot of troubleshooting with QThreads still blocking the GUI thread, I found a fix here: https://stackoverflow.com/questions/41526832/pyqt5-qthread-signal-not-working-gui-freeze. Also referenced https://github.com/r9y9/deepvoice3_pytorch/issues/5 to deal with some issues that arose from running Matplotlib on a worker thread.
