### ISSUE TITLE
Create Screen #1

### ISSUE THREAD

**Issue by p13i** [bglowniak/Air-Quality-Analysis#5]

**Comment by bglowniak** [comment]
As a user, I want to input data by browsing for a file so that it can be located by the pipeline tools.
As a user, I want to select a time range so that the data can be filtered and analyzed within the time period I am specifically interested in.
As a user, I want to specify data columns (e.g. temperature, humidity, dew point, sulfur dioxide concentration, etc.) from the air quality sensors so that only those columns selected can be processed later.
As a user, I want to specify an output path for my reports and visualizations to be deposited so that I can find them and view them later.
